### ISSUE TITLE
Rails.application.assets.find_asset and 3.0.0

### ISSUE THREAD

**Issue by maia** [rails/sprockets-rails#311]
Until `2.3.3` I was able to use the following in `application.slim` to load controller-specific js/css:

````
== stylesheet_link_tag params[:controller] if ::Rails.application.assets.find_asset("#{params[:controller]}.css")
````
With the update to `3.0.0`,  `Rails.application.assets.find_asset()` seems to return `nil` in production:
````
ActionView::Template::Error (undefined method `find_asset' for nil:NilClass)
````
How would I need to change my code to let add controller-specific css/js? So far, I've only found [mileszs/wicked_pdf/issues/476](https://github.com/mileszs/wicked_pdf/issues/476) suggesting to use `assets.compile = true` and also links a rather complicated commit. I'm unsure if it's a workaround and what the recommended way is. If the best solution is to not have controller-specific css/js but to put everything in a single file, that's fine with me too.

**Comment by mattbrictson** [comment]
One way might be to use the `asset_path` helper to test existence of the asset. It returns different things based on whether it can find the asset.

If the asset does not exist (i.e. it is not precompiled):

```ruby
asset_path("does-not-exist.css")
# => "/does-not-exist.css"
```

Whereas if the asset does exist:

```ruby
asset_path("application.css")
# => "/assets/application-46ae33e78e504ff295219f41d63c79719d062e48dc0c07bd9b6f7bcad72c6636.css"
```

**Comment by maia** [comment]
Thanks. I've now also found the suggestion of using `assets_manifest[filename]`, but I'm unsure which solution is just a workaround that might break any time soon, and which is the suggested way to go.

**Comment by mattbrictson** [comment]
Yes, `assets_manifests` is a cleaner solution. It took me a few tries to figure out the API. You can use it like this:

```ruby
Rails.application.assets_manifest.assets["application.css"]
=> "application-46ae33e78e504ff295219f41d63c79719d062e48dc0c07bd9b6f7bcad72c6636.css"
Rails.application.assets_manifest.assets["does-not-exist.css"]
=> nil
```

**Comment by rafaelfranca** [comment]
Yes. assets_manifest is the public api for that. It is already present in the view layer so you don't need to use Rails application

**Comment by maia** [comment]
@rafaelfranca and @mattbrictson : Thanks for your input, but unfortunately I cannot get this to work using sprockets 3.5.2 and sprockets-rails 3.0.0, in development mode I'm seeing the following:
````
# in application.slim:
== stylesheet_link_tag params[:controller] if assets_manifest["#{params[:controller]}.css"]

# which raises:
undefined method `[]' for #<Sprockets::Manifest:0x007facd97e8280>

# and in console aven application.css isn't available:
> Rails.application.assets_manifest.assets["application.css"]
=> nil
````
Is this only supposed to work in production mode, and if yes, how would I need to check for the existence of a controller-specific .css or .js that works in both production and development mode? Thanks!

**Comment by mattbrictson** [comment]
> undefined method '[]'

You need `assets_manifest.assets[...]`, not `assets_manifest[...]`.

> [is there a solution that] works in both production and development mode?

I haven't figure this out either.

**Comment by maia** [comment]
@mattbrictson I updated my comment, I did try both. The previous suggestion was made by @rafaelfranca at #294.

**Comment by maia** [comment]
@rafaelfranca what's your suggestion on how to check for existence of a controller-specific .css or .js that works in both production and development mode? Thanks!

**Comment by rafaelfranca** [comment]
My suggestion is don't do that. Really, this add a complexity to your system that is not wort. If you really want to do that you can use [`resolve_asset_path`](https://github.com/rails/sprockets-rails/blob/2f0a100c56eba6812b5967e9df32e647f69127bb/lib/sprockets/rails/helper.rb#L88). It is private API and may break in the next release. And no, we don't plan to support this kind of feature for the long term. I personally consider it a bad practice so I prefer to no support it in this gem.

**Comment by maia** [comment]
Thanks, that's fine with me – I've merged all my controller-specific css and upgraded to 3.0.0 without problems.

**Comment by miks** [comment]
Till now if I had something like 10 controllers with unique js for each, it was very simple to include js only if it exists. How can this be bad practise? I guess it's bad practise to include 10 controller specific js assets and use only one of them (in the meantime all 10 js is running onReady handlers, searching for controller specific DOM/etc..).

**Comment by miks** [comment]
@rafaelfranca do you have other suggestion than compile all javascripts in one big file?

**Comment by miks** [comment]
Also discovered problem when assets is not explicitly cleared. Assets now is returning previous version   that does not exists anymore ex. `Rails.application.assets_manifest.assets["does-not-exist-anymore.css"]`.
If I understand correctly, before 3.x sprockets resolved assets upon existing path in application not compiled assets.
